# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

jobs:
  playstore_upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Download app artifact
        uses: actions/download-artifact@v2
        with:
          name: app-release.aab
          
          
      - name: display structure
        run: ls -R
